"use client";

import React from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { PenLine, ShieldCheck } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: '#12121a', color: '#e8e0d4' }}>
      <header className="fixed top-0 left-0 right-0 z-50 glass border-b border-[#2a2a3a] px-6 py-4 flex items-center justify-between">
        <Link href="/" className="flex items-center space-x-2">
          <div className="h-9 w-9 bg-gradient-to-br from-[#c9a96e] to-[#b8944a] rounded-lg flex items-center justify-center">
            <PenLine className="h-5 w-5 text-white" />
          </div>
          <span className="text-xl font-bold tracking-tight text-white" style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>One Post AI</span>
        </Link>
        <nav className="hidden md:flex items-center space-x-8 text-sm font-medium text-slate-300">
          <Link href="/about" className="hover:text-white transition-colors">About</Link>
          <Link href="/contact" className="hover:text-white transition-colors">Contact</Link>
          <Link href="/faq" className="hover:text-white transition-colors">FAQ</Link>
          <Link href="/pricing" className="hover:text-white transition-colors">Pricing</Link>
        </nav>
        <Link href="/dashboard"><Button variant="primary" size="sm">Launch App</Button></Link>
      </header>

      <main className="pt-32 pb-24 px-6 max-w-4xl mx-auto">
        <div className="mb-12">
          <h1 className="text-5xl font-extrabold tracking-tight mb-4" style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>Terms of Service</h1>
          <p className="text-slate-400 text-sm">Last updated: June 25, 2026</p>
        </div>

        <div className="space-y-8 text-slate-300 leading-relaxed">
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
            <p>By accessing or using One Post AI (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">2. Description of Service</h2>
            <p>One Post AI is an AI-powered content creation and publishing platform. The Service helps users create, schedule, and publish content across multiple social media platforms from one place.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">3. User Accounts</h2>
            <p>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must provide accurate information during registration.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">4. Subscription and Payments</h2>
            <p>We offer tiered subscription plans. Payments are processed securely through Stripe. By subscribing, you agree to pay all fees associated with your selected plan and authorize recurring charges until cancellation. All plans include a 30-day money-back guarantee.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">5. Acceptable Use</h2>
            <p>You agree not to use the Service for any illegal purpose, to spam or harass others, to post harmful or deceptive content, or to interfere with the proper functioning of the Service.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">6. AI-Generated Content Disclaimer</h2>
            <p>Content generated by One Post AI is created using artificial intelligence and should be reviewed before publishing. We make no guarantees about the accuracy, appropriateness, or performance of AI-generated content. You are solely responsible for any content you publish.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">7. Intellectual Property</h2>
            <p>You retain ownership of any content you create using the Service. The Service itself, including its code, design, and underlying technology, is owned by One Post AI and Aura Haven Tech.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">8. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, One Post AI and Aura Haven Tech shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">9. Termination</h2>
            <p>We reserve the right to suspend or terminate your account at any time for violation of these terms. You may cancel your account at any time from your dashboard.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">10. Contact</h2>
            <p>For questions about these Terms of Service, please contact us at:</p>
            <p className="mt-3" style={{ color: '#c9a96e' }}>support@onepostai.app</p>
            <p className="text-slate-400 text-sm">Aura Haven Tech<br />Part of the Axel AI family of brands</p>
          </section>
        </div>
      </main>

      <footer className="border-t border-[#2a2a3a] py-12 px-6 text-slate-500 text-sm">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between">
          <div className="flex items-center space-x-2 mb-4 md:mb-0">
            <PenLine className="h-4 w-4" style={{ color: '#c9a96e' }} />
            <span className="font-bold text-white" style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>One Post AI</span>
          </div>
          <div className="flex flex-wrap justify-center gap-x-6 gap-y-2 text-slate-400 mb-4 md:mb-0">
            <Link href="/about" className="hover:text-white transition-colors">About</Link>
            <Link href="/contact" className="hover:text-white transition-colors">Contact</Link>
            <Link href="/faq" className="hover:text-white transition-colors">FAQ</Link>
            <Link href="/privacy" className="hover:text-white transition-colors">Privacy</Link>
            <Link href="/terms" className="text-white">Terms</Link>
            <Link href="/pricing" className="hover:text-white transition-colors">Pricing</Link>
            <Link href="/dashboard" className="hover:text-white transition-colors">Dashboard</Link>
            <a href="https://aurahaven.shop" target="_blank" className="hover:text-white transition-colors">Aura Haven</a>
            <a href="https://autoexec-nine.vercel.app" target="_blank" className="hover:text-white transition-colors">Axel AI</a>
          </div>
          <div className="text-center md:text-right">
            <div className="flex items-center justify-center md:justify-end gap-2 text-emerald-400 text-xs mb-1">
              <ShieldCheck className="h-3.5 w-3.5" />
              <span>30-day money-back guarantee</span>
            </div>
            <div>&copy; {new Date().getFullYear()} One Post AI Inc.</div>
          </div>
        </div>
      </footer>
    </div>
  );
}